name: Build Application and Make Release

on:
  push:
    tags:
      - '*'

jobs:
   build_release:
     name: Build Release
     uses: ./.github/workflows/build.yml
     with:
       build_type: Release
       is_qt_cached: false
     secrets: inherit

   create_release:
    needs: build_release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          path: 'PrismLauncher-source'

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      
      - name: Package artifacts properly
        shell: bash
        run: |
          mv ${{ github.workspace }}/PrismLauncher-source PrismLauncher-${{ env.VERSION }}

          if compgen -G "PrismLauncher-Linux-Qt6-Portable*/PrismLauncher-portable-*.tar.gz" > /dev/null; then
            find PrismLauncher-Linux-Qt6-Portable* -name "PrismLauncher-portable-*.tar.gz" -exec cp {} . \;
          fi

          if compgen -G "PrismLauncher-Linux-Qt6*/PrismLauncher-*.tar.gz" > /dev/null; then
            find PrismLauncher-Linux-Qt6* -name "PrismLauncher-*.tar.gz" -exec cp {} . \;
          fi

          if compgen -G "PrismLauncher-Linux-Portable*/PrismLauncher-portable-*.tar.gz" > /dev/null; then
            find PrismLauncher-Linux-Portable* -name "PrismLauncher-portable-*.tar.gz" -exec cp {} . \;
          fi

          if compgen -G "PrismLauncher-Linux*/PrismLauncher-*.tar.gz" > /dev/null; then
            find PrismLauncher-Linux* -name "PrismLauncher-*.tar.gz" -exec cp {} . \;
          fi

          if compgen -G "PrismLauncher-*.AppImage/PrismLauncher-*.AppImage" > /dev/null; then
            find PrismLauncher-*.AppImage -name "*.AppImage" -exec cp {} . \;
          fi

          if compgen -G "PrismLauncher-macOS-Legacy*/PrismLauncher.tar.gz" > /dev/null; then
            mv PrismLauncher-macOS-Legacy*/PrismLauncher.tar.gz PrismLauncher-macOS-Legacy-${{ env.VERSION }}.tar.gz
          fi

          if compgen -G "PrismLauncher-macOS*/PrismLauncher.tar.gz" > /dev/null; then
            mv PrismLauncher-macOS*/PrismLauncher.tar.gz PrismLauncher-macOS-${{ env.VERSION }}.tar.gz
          fi

          tar -czf PrismLauncher-${{ env.VERSION }}.tar.gz PrismLauncher-${{ env.VERSION }}

          for d in PrismLauncher-Windows-MSVC*; do
            cd "${d}" || continue
            LEGACY="$(echo -n ${d} | grep -o Legacy || true)"
            ARM64="$(echo -n ${d} | grep -o arm64 || true)"
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="PrismLauncher-Windows-MSVC"
            test -z "${LEGACY}" || NAME="${NAME}-Legacy"
            test -z "${ARM64}" || NAME="${NAME}-arm64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv PrismLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

          for d in PrismLauncher-Windows-MinGW-w64*; do
            cd "${d}" || continue
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="PrismLauncher-Windows-MinGW-w64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv PrismLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done
      
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
          tag_name: ${{ github.ref }}
          name: Prism Launcher ${{ env.VERSION }}
          draft: true
          prerelease: false
         
        files: |
           PrismLauncher-Linux*.tar.gz
           PrismLauncher-Linux*.AppImage
           PrismLauncher-Windows-MinGW-w64-${{ github.ref_name }}.zip
           PrismLauncher-Windows-MinGW-w64-Portable-${{ github.ref_name }}.zip
           PrismLauncher-Windows-MinGW-w64-Setup-${{ github.ref_name }}.exe
           PrismLauncher-Windows-MSVC-Legacy-${{ github.ref_name }}.zip
           PrismLauncher-Windows-MSVC-Legacy-Portable-${{ github.ref_name }}.zip
           PrismLauncher-Windows-MSVC-Legacy-Setup-${{ github.ref_name }}.exe
           PrismLauncher-Windows-MSVC-arm64-${{ github.ref_name }}.zip
           PrismLauncher-Windows-MSVC-arm64-Portable-${{ github.ref_name }}.zip
           PrismLauncher-Windows-MSVC-arm64-Setup-${{ github.ref_name }}.exe
           PrismLauncher-Windows-MSVC-${{ github.ref_name }}.zip
           PrismLauncher-Windows-MSVC-Portable-${{ github.ref_name }}.zip
           PrismLauncher-Windows-MSVC-Setup-${{ github.ref_name }}.exe
           PrismLauncher-macOS-${{ github.ref_name }}.tar.gz
           PrismLauncher-macOS-Legacy-${{ github.ref_name }}.tar.gz
           PrismLauncher-${{ github.ref_name }}.tar.gz